set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#7E7778 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#8A7575 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#6D5A5A guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#7E7778 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#160909 guibg=#C3C1C1 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#8A7575 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#6A6C7C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#6F6B70 guibg=NONE guisp=#6F6B70 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#7397C9 guibg=NONE guisp=#7397C9 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#6A748A guibg=NONE guisp=#6A748A blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#8B807E guibg=NONE guisp=#8B807E blend=NONE gui=underline
highlight DiagnosticWarn guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#847875 guibg=#6D5A5A guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#A59C9C guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#6F6B70 guibg=#6D5A5A guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#6F6B70 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#6A748A guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#847875 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#6A748A guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#6F6B70 guibg=#C3C1C1 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#6F6B70 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#7E7778 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#6A748A guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#C3C1C1 guibg=#6D5A5A guisp=NONE blend=NONE gui=italic
highlight Function guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#6D5A5A guibg=#7E7778 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#A59C9C guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C3C1C1 guibg=#A59C9C guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#6D5A5A guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#6A748A guibg=NONE guisp=#A59C9C blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#6A6C7C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#6A6C7C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#C3C1C1 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#C3C1C1 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#8B807E guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#8A7575 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#160909 guibg=#7397C9 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#160909 guibg=#6A748A guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#160909 guibg=#847875 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#160909 guibg=#BAABBF guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#160909 guibg=#6F6B70 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#160909 guibg=#7E7778 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#6D5A5A guibg=#7E7778 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#A59C9C guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#847875 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#C3C1C1 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#8A7575 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#C3C1C1 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#A59C9C guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#6F6B70 guibg=#C3C1C1 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#A59C9C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#7E7778 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#C3C1C1 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C3C1C1 guibg=#6A748A guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#8A7575 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#A59C9C guibg=#8B807E guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#8A7575 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#6A6C7C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#A59C9C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#6F6B70 guibg=NONE guisp=#6F6B70 blend=NONE gui=underline
highlight SpellCap guifg=#8B807E guibg=NONE guisp=#8B807E blend=NONE gui=underline
highlight SpellLocal guifg=#7397C9 guibg=NONE guisp=#7397C9 blend=NONE gui=underline
highlight SpellRare guifg=#BAABBF guibg=NONE guisp=#BAABBF blend=NONE gui=underline
highlight Statement guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#C3C1C1 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#8A7575 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#847875 guibg=#847875 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#8B807E guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#A59C9C guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#A59C9C guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#847875 guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#8B807E guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#160909 guibg=#8A7575 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C3C1C1 guibg=#6A748A guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#C3C1C1 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#8A7575 guibg=#160909 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#6A6C7C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#6A6C7C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#847875 guibg=#6D5A5A guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#6F6B70 guibg=#6D5A5A guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#BAABBF guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#847875 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#7397C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#8B807E guibg=#6D5A5A guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#6D5A5A guisp=NONE blend=NONE gui=underline
highlight @type guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#6A748A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#8B807E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#6F6B70 guibg=NONE guisp=NONE blend=NONE gui=NONE
